apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 15m
  path: ./operators/cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cnpg-system
  wait: true
