apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          env:
            - name: DATABASE_HOST
              value: "cnpg-primary.cast-cnpg.svc.cluster.local"
            - name: DATABASE_NAME
              value: "castdb"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cnpg-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-credentials
                  key: password
