apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 15m
  releaseName: cnpg-system
  targetNamespace: cnpg-system
  createNamespace: true
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.22.0"  # you can lock to a specific version if needed
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: false
