apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: backend
          image: ghcr.io/example/backend:1.1.0-qa
          ports:
            - containerPort: 5000
          env:
            - name: APP_MODE
              value: "qa"
            - name: LOG_LEVEL
              value: "debug"
